#!/usr/bin/bash
#
# Partitioning the disk

# Format the partitoins

# Mount the filesystem

# Select the mirrors
curl 'https://archlinux.org/mirrorlist/?country=IR&protocol=http&protocol=https&ip_version=4' | cut -c2- | tee /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
##curl 'https://archlinux.org/mirrorlist/?country=IR&protocol=http&protocol=https&ip_version=4' | cut -c2- > /etc/pacman.d/mirrorlist


# Updating the system clock
timedatectl set-ntp true

help()
{
    echo -e "Usage: arch-install <state> <DE/WM>"
}

pacstrap_packages='base base-devel linux'
if [ -n $1 ]; then # -n -- True if the string is non-zero.
    case $1 in 
        'vm')               
            pacstrap /mnt $pacstrap_packages
        ;;

        'metal')            
            pacstrap /mnt $(echo "$pacstrap_packages") linux-firmware
        ;;    
        
        *) 
            echo "Invalid input."
            help
            exit 1
        ;;

    esac

else
    echo "No input."
    help
    exit 1
fi
#  Configuring the system
genfstab -U /mnt >> /mnt/etc/fstab

##cp install2 /mnt 
#hello='a'
#cat <<EOF > /mnt/install2
##!/bin/bash
#echo $hello
#EOF

cat <<EOF > /mnt/install2
#!/usr/bin/bash

# Set timezone
ln -sf /usr/share/zoneinfo/Asia/Tehran /etc/localtime
hwclock --systohc

# Localization
sed -i '177s/.//' /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" >> /etc/locale.conf

# Network Configuration
echo "swartz" >> /etc/hostname

# /Creating /etc/hosts
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1 localhost" >> /etc/hosts
echo "127.0.1.1 swartz.localdomain swartz" >> /etc/hosts

# Root Password
passwd

# Installing bootloader and networkmanger and configuring them
pacman -S --noconfirm grub networkmanager
grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
systemctl enable NetworkManager

# Installing other neccessary packages pacman -S --noconfirm xorg xorg-server gnome firefox vlc goldendict nautilus dolphin konsole telegram-desktop calibre gnome-shell gnome-tweaks git
#systemctl enable gdm.service

useradd -mG wheel ali
passwd ali
sed -i '85s/..//' /etc/sudoers

#echo "exec i3" > /home/ali/.xinitrc

necessary_packages="xorg nautilus dolphin konsole alacritty exa bat vim mlocate fish zsh zsh-autosuggestions zsh-completions zsh-syntax-highlighting openssh" 
# Installing other neccessary packages pacman -S --noconfirm xorg xorg-server gnome firefox vlc goldendict nautilus dolphin konsole telegram-desktop calibre gnome-shell gnome-tweaks git

if [ -n $2 ]; then # -n -- True if the string is non-zero.
    case $2 in 
        'i3')               
            pacman --noconfirm -S $(echo $necessary_packages) xorg-xinit i3-gaps i3blocks dmenu noto-fonts noto-fonts-emoji kvantum-qt5 qt5ct lxsession
            mkdir /home/ali
            echo "exec i3" > /home/ali/.xinitrc
        ;;

        #'gnome')            
        #    pacstrap /mnt "echo $pacstrap_packages linux-firmware"
        #;;    

        #'kde')               
        #    pacstrap /mnt $pacstrap_packages
        #;;

        *)
            echo "$2 is not in the list of DE/WMs."
            help
            exit 1
    esac

else
    echo "No input"
    help
    exit 1
fi
EOF

chmod +x /mnt/install2
arch-chroot /mnt ./install2
