#!/bin/bash

#connecting to wifi
echo "ctrl_interface=/run/wpa_supplicant" >> /etc/wpa_supplicant/wpa_supplicant-wlp9s0.conf
echo "update_config=1" >> /etc/wpa_supplicant/wpa_supplicant-wlp9s0.conf
wpa_passphrase Soghra @Thugstools1 >> /etc/wpa_supplicant/wpa_supplicant-wlp9s0.conf
wpa_supplicant -B -i wlp9s0 -c /etc/wpa_supplicant/wpa_supplicant-wlp9s0.conf
