#!/usr/bin/bash

#connecting to wifi
#echo "ctrl_interface=/run/wpa_supplicant" >> /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
#echo "update_config=1" >> /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
#wpa-passphrase Soghra @Thugstools1 >> /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
#wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant-wlan0.conf

# Partitioning the disk

# Format the partitoins

# Mount the filesystem

# Select the mirrors
#curl https://archlinux.org/mirrorlist/?country=IR&protocol=http&protocol=https&ip_version=4 | cut -c2- | tee /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
curl 'https://archlinux.org/mirrorlist/?country=IR&protocol=http&protocol=https&ip_version=4' | cut -c2- > /etc/pacman.d/mirrorlist

# Updating the system clock
timedatectl set-ntp true

# Install essential packages
pacstrap /mnt base base-devel linux linux-firmware vim man-db

#  Configuring the system
#genfstab -U /mnt >> /mnt/etc/fstab

