#!/usr/bin/bash

#connecting to wifi
#echo "ctrl_interface=/run/wpa_supplicant" >> /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
#echo "update_config=1" >> /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
#wpa-passphrase Soghra @Thugstools1 >> /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
#wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant-wlan0.conf

# Partitioning the disk

# Format the partitoins

# Mount the filesystem

# Select the mirrors
#curl https://archlinux.org/mirrorlist/?country=IR&protocol=http&protocol=https&ip_version=4 | cut -c2- | tee /etc/pacman.d/mirrorlist /mnt/etc/pacman.d/mirrorlist
curl 'https://archlinux.org/mirrorlist/?country=IR&protocol=http&protocol=https&ip_version=4' | cut -c2- > /etc/pacman.d/mirrorlist

# Updating the system clock
timedatectl set-ntp true

# Install essential packages
pacstrap /mnt base base-devel linux linux-firmware vim man-db

#  Configuring the system
#genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt
ping google.com
# Chroot

## Set timezone
#ln -sf /usr/share/zoneinfo/Asia/Tehran /etc/localtime
#hwclock --systohc
#
## Localization
#sed -i '177s/.//' /etc/locale.gen
#locale-gen
#echo "LANG=en_US.UTF-8" >> /etc/locale.conf
#
## Network Configuration
#echo "swartz" >> /etc/hostname
#
## /Creating /etc/hosts
#echo "127.0.0.1 localhost" >> /etc/hosts
#echo "::1 localhost" >> /etc/hosts
#echo "127.0.1.1 swartz.localdomain swartz" >> /etc/hosts
#
## Root Password
#passwd
#
## Installing bootloader and networkmanger and configuring them
#pacman -S --noconfirm grub networkmanager
#grub-install /dev/sda
#grub-mkconfig -o /boot/grub/grub.cfg
#systemctl enable NetworkManager
#
## Installing other neccessary packages
#pacman -S --noconfirm xorg xorg-server gnome firefox vlc goldendict nautilus dolphin konsole telegram-desktop calibre gnome-shell gnome-tweaks git
#
#systemctl enable gdm.service
#
#useradd -mG wheel ali
#passwd ali
#sed -i '85s/..//' /etc/sudoers
#
##cd /home/ali
##git clone https://aur.archlinux.org/yay.git
##cd yay
##makepkg -si
